name: Android CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew gradlew clean build
      - name: ls file
        run: |
          ls -alRZ .
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Lyric Getter release
          path: ./app/build/outputs/apk/release

